import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import ScrollTopButton from '../../components/uiParts/ScrollTopButton';

const About: NextPage = () => (
  <>
    <Head>
      <title key='title'>サービスについて | MyFridge</title>
      <meta
        key='description'
        name='description'
        content='Generated by create next app'
      />
    </Head>
    <div className='pt-28'>
      {/* タイトル */}
      <h1 className='mb-16 py-2 px-2 md:px-[32px] md:text-5xl text-3xl text-left text-custom-black font-bold'>
        サービスについて
      </h1>

      {/* 1段目 */}
      <div className='w-full md:flex md:mb-16'>
        {/* 文章側 */}
        <div className='w-full bg-custom-accent rounded-r-[150px] flex justify-center items-center'>
          <div>
            <div className='text-white text-center font-bold text-3xl px-28 pt-10 pb-10'>
              こんな時ありませんか？
            </div>
            <div className='text-white text-left text-3xl px-28 pb-10'>
              冷蔵庫に何があるか把握できていない！
              <br />
              冷蔵庫の余っている食材を使いたい！
              <br />
              冷蔵庫の整理整頓ができていない！
            </div>
          </div>
        </div>

        {/* 画像側 */}
        <div className='w-full'>
          <div className='flex items-center justify-center h-full'>
            <div className=''>
              <Image
                src='/img/lettuse.png'
                alt='レタス'
                width={400}
                height={400}
              />
            </div>
          </div>
        </div>
      </div>

      {/* 2段目 */}
      <div className='w-full md:flex md:mb-16 md:justify-end text-right'>
        {/* 文章側 */}
        <div className='w-full md:order-2 bg-custom-accent rounded-l-[150px] flex justify-center items-center'>
          <div>
            <div className='text-white text-center text-3xl font-bold px-28 pt-10 pb-10'>
              機能について
            </div>
            <div className='text-white text-left text-3xl px-28 pb-10'>
              ・冷蔵庫内の管理：食材や飲み物の名前、数量、消費期限などを入力し、冷蔵庫内の在庫を管理できます。
              <br />
              ・賞味期限アラート機能：設定した賞味期限が近づくと、通知が送られるので、食材の無駄を防止できます。
              <br />
              ・家族と共有可能：家族全員が同じアプリを使用すれば、家族で共有している冷蔵庫の在庫を共有できます。
            </div>
          </div>
        </div>

        {/* 画像側 */}
        <div className='w-full md:order-1'>
          <div className='flex items-center justify-center h-full'>
            <div className=''>
              <Image
                src='/img/carrot.png'
                alt='にんじん'
                width={400}
                height={400}
              />
            </div>
          </div>
        </div>
      </div>

      {/* 3段目 */}
      <div className='w-full md:flex md:mb-16'>
        {/* 文章側 */}
        <div className='w-full bg-custom-accent rounded-r-[150px] flex justify-center items-center'>
          <div>
            <div className='text-white text-center text-3xl font-bold px-28 pt-10 pb-10'>
              開発者について
            </div>
            <div className='text-white text-left text-3xl px-28 pb-10'>
              MM(フロントエンド/バックエンド)
              <br />
              DK(フロントエンド/バックエンド)
            </div>
          </div>
        </div>

        {/* 画像側 */}
        <div className='w-full'>
          <div className='flex items-center justify-center h-full'>
            <div className=''>
              <Image
                src='/img/chineseLettuse.png'
                alt='チャイニーズレタス'
                width={400}
                height={400}
              />
            </div>
          </div>
        </div>
      </div>

      <ScrollTopButton />
    </div>
  </>
);

export default About;
