import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import ScrollTopButton from '../../components/uiParts/ScrollTopButton';

const About: NextPage = () => (
  <>
    <Head>
      <title key='title'>サービスについて | MyFridge</title>
      <meta
        key='description'
        name='description'
        content='Generated by create next app'
      />
    </Head>
    <div className='pt-28'>
      {/* タイトル */}
      <h1 className='mb-16 py-2 px-2 md:px-[32px] md:text-5xl text-3xl text-left text-custom-black font-bold'>
        サービスについて
      </h1>

      {/* 1段目 */}
      <div className='w-full md:flex md:mb-16'>
        {/* 文章側 */}
        <div className='w-full bg-custom-accent rounded-r-[150px] flex justify-center items-center'>
          <div>
            <div className='text-white text-center font-bold text-3xl px-28 pt-10 pb-10'>
              こんな時ありませんか？
            </div>
            <div className='text-white text-center text-3xl px-28 pb-10'>
              Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
              nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
              erat, sed diam voluptua. At
            </div>
          </div>
        </div>

        {/* 画像側 */}
        <div className='w-full'>
          <div className='flex items-center justify-center h-full'>
            <div className=''>
              <Image
                src='/img/lettuse.png'
                alt='レタス'
                width={400}
                height={400}
              />
            </div>
          </div>
        </div>
      </div>

      {/* 2段目 */}
      <div className='w-full md:flex md:mb-16 md:justify-end text-right'>
        {/* 文章側 */}
        <div className='w-full md:order-2 bg-custom-accent rounded-l-[150px] flex justify-center items-center'>
          <div>
            <div className='text-white text-center text-3xl font-bold px-28 pt-10 pb-10'>
              機能について
            </div>
            <div className='text-white text-center text-3xl px-28 pb-10'>
              Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
              nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
              erat, sed diam voluptua. At
            </div>
          </div>
        </div>

        {/* 画像側 */}
        <div className='w-full md:order-1'>
          <div className='flex items-center justify-center h-full'>
            <div className=''>
              <Image
                src='/img/carrot.png'
                alt='にんじん'
                width={400}
                height={400}
              />
            </div>
          </div>
        </div>
      </div>

      {/* 3段目 */}
      <div className='w-full md:flex md:mb-16'>
        {/* 文章側 */}
        <div className='w-full bg-custom-accent rounded-r-[150px] flex justify-center items-center'>
          <div>
            <div className='text-white text-center text-3xl font-bold px-28 pt-10 pb-10'>
              開発者について
            </div>
            <div className='text-white text-center text-3xl px-28 pb-10'>
              Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
              nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
              erat, sed diam voluptua. At
            </div>
          </div>
        </div>

        {/* 画像側 */}
        <div className='w-full'>
          <div className='flex items-center justify-center h-full'>
            <div className=''>
              <Image
                src='/img/chineseLettuse.png'
                alt='チャイニーズレタス'
                width={400}
                height={400}
              />
            </div>
          </div>
        </div>
      </div>

      <ScrollTopButton />
    </div>
  </>
);

export default About;
