version: '3.8'
services:
  myfridge-landingpage:
    build:
      context: . #Dockerfileの場所
      dockerfile: Dockerfile #Dockerfileの名前
    volumes:
      - ./src:/src # ローカルのsrc配下をコンテナ内から読み書き
    ports:
      - 3001:3000
    stdin_open: true
    tty: true #コンテナが正常終了してもコンテナを継続させる
    command: npm run dev
